default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: tailwind_templates_development
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: tailwind_templates_development

test:
  <<: *default
  database: tailwind_templates_test

production:
  <<: *default
  database: tailwind_templates_production
  username: root
  password: root
